name: Python application

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: install
            run: |
                sudo -E apt-get -qq update
                sudo -E apt-get -qq install build-essential git-core
                wget --no-verbose https://github.com/jepler/esp-open-sdk/releases/download/2018-06-10/xtensa-lx106-elf-standalone.tar.gz
                zcat xtensa-lx106-elf-standalone.tar.gz | tar x
                export PATH=$(pwd)/xtensa-lx106-elf/bin:$PATH

        - name: checkout
            run: git clone --depth=5 https://github.com/micropython/micropython.git

        - name: compile micropython
            env:
                 MAKEOPTS: "-j4"
            run: |
                cd micropython
                make ${MAKEOPTS} -C mpy-cross
                make ${MAKEOPTS} -C ports/esp8266 submodules
                make ${MAKEOPTS} -C ports/esp8266
                make ${MAKEOPTS} -C ports/esp8266 BOARD=GENERIC_512K
